Walmart.Web/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Walmart.ApplicationCore.Utilities;
using Walmart.ApplicationCore.Models;
using Walmart.Infrastructure.Data;
using Walmart.Infrastructure.Interfaces;
using Walmart.ApplicationCore.ParamModels;
using Walmart.ApplicationCore.ViewModels;
using Walmart.ApplicationCore.DtoModels;
using Newtonsoft.Json;
using static Walmart.ApplicationCore.Models.Product;

namespace Walmart.Web.Controllers;
[Area("Admin")]
[Authorize(Roles = WebsiteRole.Admin)]
    public class DashboardController : BaseController
    {
        #region Constructors
        private IWebHostEnvironment _env;
        private string? serverdestinationpath { get; set; }
        public DashboardController(IUnitOfWork uow, IWebHostEnvironment env) : base(uow)
        {
            _env = env;
        }
        #endregion
        // GET: Admin/Movies
        public IActionResult Index()
        {   
            DashboardDto dashboardDto = new DashboardDto();
            var totalorder = _uow.Orders.GetAll().Count();
            var pendingorder = _uow.Orders.GetAll(p => p.Order_Status == "Pending").Count();
            var paidorder = _uow.Orders.GetAll(p => p.Order_Status == "Paid").Count();
            var shippingorder = _uow.Orders.GetAll(p => p.Order_Status == "Shipping").Count();
            var users = _uow.ApplicationUsers.GetAll();
            var customerid = _uow.ApplicationUsers.GetUserRole("Customer");
            var customercount = 0;
            var managerid = _uow.ApplicationUsers.GetUserRole("Manager");
            var managercount = 0;
            var adminid = _uow.ApplicationUsers.GetUserRole("Admin");
            var admincount = 0;
            var totaluser = users.Count();
            foreach(var user in users){
                var checkrole = _uow.ApplicationUsers.CheckRole(user.Id);
                if(checkrole == customerid){
                    customercount++;
                }else if(checkrole == managerid){
                    managercount++;
                }else{
                    admincount++;
                }
            }
            var orders = _uow.Orders.GetAll(p => p.Order_Status == "Paid");
            decimal dec = 0;
            foreach (var order in orders)
            {
                dec = (decimal)(dec + order.Total_Price)!;
            }
            int totalearnings = (int)Math.Round(dec);
            var totalcategory = _uow.Categories.GetAll().Count();
            var totalsubcategory = _uow.SubCategories.GetAll().Count();
            var totalproduct = _uow.Products.GetAll().Count();
            dashboardDto.Total_Order = totalorder;
            dashboardDto.Pending_Order = pendingorder;
            dashboardDto.Paid_Order = paidorder;
            dashboardDto.Shipping_Order = shippingorder;
            dashboardDto.Total_User = totaluser;
            dashboardDto.Customer = customercount;
            dashboardDto.Manager = managercount;
            dashboardDto.Admin = admincount;
            dashboardDto.Total_Earnings = totalearnings;
            dashboardDto.Total_Category = totalcategory;
            dashboardDto.Total_Subcategory = totalsubcategory;
            dashboardDto.Total_Product = totalproduct;
            return View(dashboardDto);
        }
        
        public IActionResult ManageUsers(int id = 1, string role = null!){
            if(role == null || role == "All"){
                Console.WriteLine("if");
                UserParam userParam = new UserParam{
                PageIndex = id, PageSize = 10
                };
                Task<UserVM> users = _uow.ApplicationUsers.GetUsersByPaging(userParam);
                ViewData["SelectedValue"] = role;
                return View(users.Result);
            }
            else{
                Console.WriteLine("else");
                UserParam userParam = new UserParam{
                PageIndex = id, PageSize = 10
                };
                Task<UserVM> users = _uow.ApplicationUsers.GetUsersByPaging2(userParam, role);
                ViewData["SelectedValue"] = role;
                return View(users.Result);
            }
        }
        public IActionResult ManageCategories(){
            var categories = _uow.Categories.GetCategories();
            return View(categories);
        }
        public IActionResult CreateCategory(){
            Category category;
            category = _uow.Categories.CreateCategory();
            _uow.Categories.Add(category);
            _uow.Save();
            return RedirectToAction(nameof(ManageCategories));
        }
        public IActionResult AddSubCategory(int id){
            SubCategory subCategory;
            subCategory = _uow.SubCategories.CreateSubCategory(id);
            _uow.SubCategories.Add(subCategory);
            _uow.Save();
            return RedirectToAction(nameof(ManageCategories));
        }
        public IActionResult CategoryDetails(int id){
            Category category;
            category = _uow.Categories.Get(id);
            return View("EditCategory", category);
        }
        [HttpPost]
        public IActionResult EditCategory(int categoryid, string categoryname, IFormFile categoryimage){
                string webRootPath = _env.WebRootPath;
                string inputfilename = String.Format("Category-{0}.jpg", categoryid);
                string uploadsPath = Path.Combine("images", "CategoryImages", inputfilename);
                string filePath = Path.Combine(webRootPath, uploadsPath);
            if(categoryimage == null || categoryimage?.Length == 0){            
                Category category = new Category();
                category = _uow.Categories.Get(categoryid);
                category.CategoryId = categoryid;
                category.Category_Name = categoryname;
                category.Category_Image = category.Category_Image;
                _uow.Categories.Update(category);
                _uow.Save();
                return RedirectToAction(nameof(ManageCategories));
            } else{
                using(FileStream stream = new FileStream(filePath, FileMode.Create)){
                    categoryimage?.CopyTo(stream);
                }
                Category category = new Category();
                category.CategoryId = categoryid;
                category.Category_Name = categoryname;
                string uploadsPath2 = uploadsPath.Replace("\\","/");
                category.Category_Image = uploadsPath2;
                _uow.Categories.Update(category);
                _uow.Save();
                return RedirectToAction(nameof(ManageCategories));
            }
        }
        [HttpPost]
        public IActionResult UpdateSubCategory(int subcategoryid, int categoryid, string subcategoryname){
            SubCategory subCategory = new SubCategory();
            subCategory.SubCategoryId = subcategoryid;
            subCategory.Category_Id = categoryid;
            subCategory.SubCategory_Name = subcategoryname;
            _uow.SubCategories.Update(subCategory);
            _uow.Save();
            return RedirectToAction(nameof(ManageCategories));
        }
        public IActionResult CreateUser(){
            return View();
        }
        public IActionResult ManageProducts(int id = 1, int categoryid = 0, int subcategoryid = 0){
            var categories = _uow.Categories.GetAll();
            ViewData["Categories"] = categories;
            if(categoryid == 0){
                Param param = new Param{
                    PageIndex = id, PageSize = 10
                };
                Task<ProductVM> products = _uow.Products.GetProductsByPaging(param);
                ViewData["selectedCategory"] = "All";
                ViewData["subcategory"] = null;
                ViewData["selectedSubcategory"] = null;
                return View(products.Result);
            }else if(categoryid != 0 && subcategoryid == 0){
                var categoryname = _uow.Categories.Get(categoryid).Category_Name;
                var subcategories = _uow.SubCategories.GetAll(p => p.Category_Id == categoryid);
                Param param = new Param{
                    PageIndex = id, PageSize = 10
                };
                Task<ProductVM> products = _uow.Products.GetProductsByPaging2(param, categoryid);
                ViewData["selectedCategory"] = categoryname;
                ViewData["subcategory"] = subcategories;
                ViewData["selectedSubcategory"] = null;
                return View(products.Result);
            }else{
                var categoryname = _uow.Categories.Get(categoryid).Category_Name;
                var subcategories = _uow.SubCategories.GetAll(p => p.Category_Id == categoryid);
                string selectedsubcategory = null!;
                foreach (var item in subcategories)
                {
                    if(item.SubCategoryId == subcategoryid){
                        selectedsubcategory = item.SubCategory_Name!;
                        break;
                    }
                }
                Param param = new Param{
                    PageIndex = id, PageSize = 10
                };
                Task<ProductVM> products = _uow.Products.GetProductsByPaging3(param, subcategoryid);
                ViewData["selectedCategory"] = categoryname;
                ViewData["subcategory"] = subcategories;
                ViewData["selectedSubcategory"] = selectedsubcategory;
                return View(products.Result);
            }
        }
        public IActionResult CreateProduct(){
            Product product;
            product = _uow.Products.CreateProduct();
            _uow.Products.Add(product);
            _uow.Save();
            return RedirectToAction(nameof(ManageProducts));
        }
        public IActionResult ProductDetails(int id, bool isPhoto = false){
            var product = _uow.Products.Get(id);

Walmart.Web/ViewComponents/ShoppingCartViewComponent.cs
using Walmart.Infrastructure.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Walmart.Web.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _context;
        public ShoppingCartViewComponent(IUnitOfWork context)
        {
            _context = context;
        }

        public IViewComponentResult Invoke()
        {
            if (User.Identity!.IsAuthenticated)
            {
                int count = 0;
                ClaimsIdentity? identity = HttpContext.User.Identity as ClaimsIdentity;
                string userid = identity!.FindFirst(ClaimTypes.NameIdentifier)!.Value;
                var items = _context.ShoppingCarts.GetAll(p => p.UserId == userid);
                foreach (var item in items)
                {
                    count = count + item.Product_Quantity;
                }
                return View(count);
            }
            else
            {
                return View(0);
            }
        }
    }
}

Walmart.Web/ViewComponents/TotalPriceViewComponent.cs
using Walmart.Infrastructure.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Walmart.Web.ViewComponents
{
    public class TotalPriceViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _context;
        public TotalPriceViewComponent(IUnitOfWork context)
        {
            _context = context;
        }

        public IViewComponentResult Invoke()
        {
            if (User.Identity!.IsAuthenticated)
            {
                decimal total = 0;
                ClaimsIdentity? identity = HttpContext.User.Identity as ClaimsIdentity;
                string userid = identity!.FindFirst(ClaimTypes.NameIdentifier)!.Value;
                var items = _context.ShoppingCarts.GetAll(p => p.UserId == userid);
                foreach (var item in items)
                {
                    var product = _context.Products.Get(item.ProductId);
                    total = total + (product.Product_Price * item.Product_Quantity);
                }
                return View(total);
            }
            else
            {
                return View(0.00);
            }
        }
    }
}

Walmart.Web/Views/Shared/_LoginPartial2.cshtml
@using Microsoft.AspNetCore.Identity
@using Walmart.ApplicationCore.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
    <div class="sidebar-box1">
      <i class="fa-solid fa-right-from-bracket" style="margin-left: 4px;"></i>
      <button id="logout" type="submit" class="sidebar-text1" style="margin-left: 3px;">Sign Out</button>
    </div>
    </form>
}
else
{
    
}

Walmart.Web/Views/Shared/_LoginPartialSmall.cshtml
@using Microsoft.AspNetCore.Identity
@using Walmart.ApplicationCore.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <div style="display: flex;margin:0">
      <img src="~/images/Main Page/4809.webp" alt="" width="10%" onclick="closeNav()" style="min-width: 28.550px;">
      <a class="a5">Hi, @UserManager.GetUserAsync(User)?.Result?.FullName</a>
    </div>
}
else
{
    <div style="display: flex;">
      <img src="~/images/Main Page/4809.webp" alt="" width="10%" onclick="closeNav()" style="min-width: 28.550px;">
      <a asp-controller="Home" asp-action="Enter_Email"><button class='button8' style="margin:0 0 0 15px;font-size:14px">Sign in or create account</button></a>
    </div>
}
</ul>

Walmart.Web/Views/Shared/_MainLayout2.cshtml
@using Walmart.Web.ViewComponents;
@using Walmart.ApplicationCore.DtoModels;
@{
  var count = 0;
}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Walmart.com | Save Money. Live Better</title>
  <link rel="icon" type="image/png" href="~/images/Main Page/4809.webp" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;500&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="~/css/style.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css" integrity="sha512-sMXtMNL1zRzolHYKEujM2AqCLUR9F2C4/05cdbxjjLSRvMQIciEPCQZo++nk7go3BtSuK9kfa/s+a4f4i5pLkw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <style>
    .owl-carousel {
      width: 96%;
      margin: 0.5% 0 0.5% 2%;
      z-index: 0;
    }

    .active::after {
      content: none !important;
    }

    .owl-carousel img {
      border-radius: 0;
    }
  </style>
</head>

<body id="body1" style="display: flex;min-height:100vh;flex-wrap:wrap">
  <div id="mySidebar" class="sidebar">
    <partial name= "_LoginPartialSmall"/>
    <div class="sidebar-box1" style="margin-top: 50px;display:none">
      <img src="./Images/Main Page/wplus-icon-blue.svg" alt="" width="8%">
      <span class="sidebar-text1" style="bottom:4.5px">Walmart +</span>
    </div>
    @if(User.IsInRole("Admin")){
    <div class="sidebar-box2">
      <i class="fa-solid fa-store"></i>
      <a class="sidebar-text1" style="text-decoration: none;color:black" asp-action="Index" asp-controller="Dashboard" asp-area="Admin">Manage Shop</a>
    </div>
    }else if(User.IsInRole("Manager")){
      <div class="sidebar-box2">
      <i class="fa-solid fa-store"></i>
      <a class="sidebar-text1" style="text-decoration: none;color:black" asp-action="Index" asp-controller="ManagerDashboard" asp-area="Manager">Manage Shop</a>
    </div>
    }
    <div class="sidebar-box2">
      <i class="fa-solid fa-receipt"></i>
      <span class="sidebar-text1">Purchase History</span>
    </div>
    <div class="sidebar-box2" style="position: relative;left: -3px;display:none">
      <i class="fa-solid fa-cart-shopping"></i>
      <span class="sidebar-text1" style="margin-left: 7px;">My Items</span>
    </div>
    <div class="sidebar-box1" style="display: none;">
      <i class="fa-solid fa-user"></i>
      <span class="sidebar-text1">Account</span>
    </div>
    <div class="sidebar-box1" style="display: none;">
      <i class="fa-solid fa-circle-question"></i>
      <span class="sidebar-text1">Help</span>
    </div>
    <div class="sidebar-box2" style="display: none;">
      <i class="fa-solid fa-heart"></i>
      <span class="sidebar-text1">Lists</span>
    </div>
    <div class="sidebar-box1" style="display:none">
      <i class="fa-solid fa-gift"></i>
      <span class="sidebar-text1">Registries</span>
    </div>
    <div class="sidebar-box2">
      <i class="fa-solid fa-bars" style="margin-left: 2px;"></i>
      <a asp-action="AllCategories" asp-controller="Home" class="sidebar-text1" style="text-decoration: none;color:black">Departments</a>
      <i class="fa-solid fa-chevron-right font-awesome1"></i>
    </div>
    <div class="sidebar-box2" style="display: none;">
      <i class="fa-solid fa-grip-vertical" style="position: relative;left: 4px;"></i>
      <span class="sidebar-text1" style="margin-left: 17px;">Services</span>
      <i class="fa-solid fa-chevron-right font-awesome1" style="left: 178px;"></i>
    </div>
    <partial name= "_LoginPartial2"/>
  </div>
  <div class="header1">
    <div class="flex-container1">
      <a asp-controller="Home" asp-action="Index" style="width: 170px; height: 52px; margin-left: 15px"><img src="~/images/Main Page/walmartLogo.svg" alt="walmart logo" class="img3" /></a>
      <button class="fa-solid fa-bars icon" id="two">
        <span class="icontext">Departments</span>
      </button>
      <button class="fa-solid fa-grip-vertical icon" style="width: 110px;display:none" onclick="openNav()" id="service">
        <span class="icontext">Services</span>
      </button>
      <form method="post" onsubmit="return checkinput('inside1')" asp-action="SearchProductsbyName" class="placeholder1">
        <input type="text" placeholder="Search everything at Walmart online and in store" class="inside1" name="productname"/>
        <button class="fa-solid fa-magnifying-glass button1 insidebtn1" type="submit"></button>
      </form>
      <form method="post" onsubmit="return checkinput('inside2')" asp-action="SearchProductsbyName" class="placeholder2">
        <input type="text" placeholder="Search Walmart" class="inside2" />
        <button class="fa-solid fa-magnifying-glass button1 insidebtn1" type="submit"></button>
      </form>
      <button class="fa-solid fa-magnifying-glass button1" type="submit" style="visibility: hidden;"></button>
      <button class="fa-regular fa-heart icon2" id="icon2" style="display: none;">
        <span class="icontext2">Reorder <br /><span style="font-weight: bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;My
            Items</span></span>
      </button>
      <partial name= "_LoginPartial"/>
      <partial name= "_LoginPartial3">
        @if(@User.Identity!.IsAuthenticated){
        <a asp-action="CartDetails" asp-area="Customer">
          <button class="fa-solid fa-cart-shopping icon3" style="right: 15px; padding-left: 14px">
          @await Component.InvokeAsync("TotalPrice") @await Component.InvokeAsync("ShoppingCart")
          </button>
        </a>
        }else{
        <a asp-action="Enter_Email" asp-area="Customer">
          <button class="fa-solid fa-cart-shopping icon3" style="right: 15px; padding-left: 14px">
          <span class="icontext3">$0.00</span><span class="icontext4">0</span>
          </button>
        </a>
        }
    </div>
    <div class="flex-container2">
      <button class="fa-solid fa-bars icon7" onclick="openNav()" id="sc1"></button>
      <a asp-action="Index" asp-area="Customer" style="height: 50px; width: 50px; margin-right: 15px" id="img4"><img src="~/images/Main Page/4809.webp" alt="" class="img4" /></a>
      <form method="post" onsubmit="return checkinput('inside3')" class="placeholder3">
        <input type="text" placeholder="Search Walmart" class="inside3" />
        <button class="fa-solid fa-magnifying-glass button1 insidebtn2" type="submit"></button>
      </form>
      <button class="fa-solid fa-magnifying-glass button1" style="visibility: hidden;" type="submit"></button>
        <span class="icontext3" style="left: 12px">$0.00</span><span class="icontext4">0</span>
      </button>
    </div>
    <div class="header2">
      <button style="flex-shrink: 0; width: 620px; margin-left: 10px;display:flex" id="btn1">
        <img src="~/images/Main Page/Holding Phone Icon.webp" alt="" class="img1" />
        <span class="icontext5" id="txt1">Shop Address</span>
        <span class="icontext6" style="bottom: 1px; margin-right: 8px">|</span>
        <p class="fa-solid fa-location-dot" style="color: white;margin: auto 0" id="i1"></p>
        <span class="icontext6">6TH East Ave</span>
        <p class="fa-solid fa-house icon4" style="bottom: 0.5px;margin:auto 0 auto 8px" id="i2"></p>
        <span class="icontext6">Austin Supercenter</span>
      </button>
      <div style="width: 100%"></div>
      <div style="position: relative; margin: 9px 30px 0 0; flex-shrink: 0">
        @foreach (var category in (List<MainPageCategoriesDto>)ViewData["MainPageData"]!)
        {
        if(count == 7){
          break;
        }else {
          count++;
          <a id="l@(count)" style="color: white;">@category.Category_Name</a>
        }
        }
      </div>
    </div>
  </div>
  <div class="button3" id="one">
    <div class="dropdown1" id="dd1">
      <a asp-action="AllCategories">All Departments</a>
      @foreach (var category in (List<MainPageCategoriesDto>)ViewData["MainPageData"]!)
      {
        <button class="five">
        <div class="hover1" id="three"></div>
        <span>@category.Category_Name</span>
        </button>
      }    
    </div>
    @foreach (var category in (List<MainPageCategoriesDto>)ViewData["MainPageData"]!)
    {
    int categoriespercolumn = (int)Math.Ceiling(category.SubCategories!.Count() /2.0);
    <div class="dropdown2" style="max-height: 586px;">
      <div class="column" id="cate2">
      <a style="font-weight: 700;cursor:pointer;color:black;text-decoration:none" href="@Url.Action("SearchProducts", "Home", new { categoryid = @category.CategoryId})">@category.Category_Name</a>
      @foreach (var subcategory in category.SubCategories!.Take(categoriespercolumn))
      {
        <a style="color:black;text-decoration:none" href="@Url.Action("SearchProducts", "Home", new { subcategoryid = @subcategory.SubCategoryId})">@subcategory.SubCategory_Name</a>
      }
      </div>
      <div class="column" id="cate4">
      <a style="font-weight: 700;visibility:hidden">@category.Category_Name</a>
      @foreach (var subcategory in category.SubCategories!.Skip(categoriespercolumn))
      {
        <a style="color:black;text-decoration:none" href="@Url.Action("SearchProducts", "Home", new { subcategoryid = @subcategory.SubCategoryId})">@subcategory.SubCategory_Name</a>
      }
      </div>
      <div class="column3">
      <img src="~/@category.Category_Image" alt="" width="100%">
      <a style="font-weight: 700;color:black;text-decoration:none" href="@Url.Action("SearchProducts", "Home", new { categoryid = @category.CategoryId})">@category.Category_Name</a>
      <button class="button5" style="width: 140px; margin:0">
          Shop Now
        </button>
      </div>
    </div>
    }
    <div class="dropdown2" style="max-height: 586px;width: fit-content;">
      <div style="margin: 0 20px 0 0; float: left; font-weight: 700">
        Electronics
        <p>Apple</p>
        <p>Gateway</p>
        <p>HP</p>
        <p>onn.</p>
        <p>Samsung</p>
        Toys & Video Games
        <p>Shop all toy brands</p>
        <p>Barbie</p>
        <p>Disney</p>
        <p>LEGO</p>
        <p>LOL</p>
        <p>Nintendo</p>
        <p>PS5</p>
        <p>Squishmallow</p>
        <p>XBOX</p>
        Sports & Outdoors
        <p>Abu Garcia</p>
        <p>Athletic Works</p>
        <p>Coleman</p>
        <p>Ozark Trail</p>
        <p>Rawlings</p>
        Baby
        <p>Evenflo</p>
        <p>Gerber</p>
        <p>Pampers</p>
        <p>Parent's Choice</p>
        <p>Similac</p>
      </div>
      <div style="float: left; margin: 0 20px 0 20px; font-weight: 700">
        Clothing, Shoes & <br />
        Accessories
        <p>Bonobos Fielder</p>
        <p>Celebrity Pink</p>
        <p>Champion</p>
        <p>Eloquii Elements</p>
        <p>Free Assembly</p>
        <p>Levis</p>
        <p>Love & Sports</p>
        <p>Justice</p>
        <p>Madden NYC</p>
        <p>Reebok</p>
        <p>Sam & Libby</p>
        <p>Scoop</p>
        <p>Sofia Vergara Jeans</p>
        Househole Essentials
        <p>Bounty</p>
        <p>Great Value</p>
        <p>Safety</p>
        <p>Tide</p>
        Home Improvement
        <p>Delta</p>
        <p>HART</p>
        <p>Hyper Tough</p>
        <p>Lasko</p>
      </div>
      <div class="dropdown3" style="bottom: 30px;">
        <img src="~/images/Main Page/dropdown2.jpg" alt="" style="width: 100%; border-radius: 0; padding: 15px 15px 0 15px" />
        <p style="font-weight: 700; font-size: 18px; margin-left: 15px" id="special">
          Discover KitchenAid
        </p>
        <p style="font-weight: 300; font-size: 14px; margin-left: 15px" id="special">
          Unleash your creativity with premium appliances and kitchenware.
        </p>
        <button class="button5" style="width: 140px; margin: 25px 0 0 15px">
          Shop Now
        </button>
      </div>
    </div>
  </div>
  @RenderBody()
  <div class="flex-container6" id="fc6" style="margin-top:auto;position:static">
      <div style="width: 30%" id="copyrights1">
        <span style="font-size: 12px; font-weight: 300">
          <span class="fa-regular fa-copyright" style="margin: 30px 2px 50px 20%" id="copyrights2"></span>
          2022 Walmart. All Rights Reserved.
        </span>
      </div>
      <div style="width: 70%" id="copyrights3">
        <a href="#" class="a8">CA Private Rights</a>
        <a href="" class="a8">Your Privacy Choices</a>
        <a href="" class="a8">Request My Personal Information</a>
        <a href="" class="a8"> California Supple Chains Act</a>
      </div>
    </div>
  <script src="~/js/script.js"></script>
  <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="~/js/script2.js"></script>
  <script src="~/js/script3.js"></script>
  @await RenderSectionAsync("Scripts", required: false)
</body>
</html>