Walmart.Web/Areas/Manager/Controllers/ManagerDashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Walmart.ApplicationCore.Utilities;
using Walmart.ApplicationCore.Models;
using Walmart.Infrastructure.Data;
using Walmart.Infrastructure.Interfaces;
using Walmart.ApplicationCore.ParamModels;
using Walmart.ApplicationCore.ViewModels;
using Walmart.ApplicationCore.DtoModels;
using Newtonsoft.Json;
using static Walmart.ApplicationCore.Models.Product;

namespace Walmart.Web.Controllers;
[Area("Manager")]
[Authorize(Roles = WebsiteRole.Manager)]
    public class ManagerDashboardController : BaseController
    {
        #region Constructors
        private IWebHostEnvironment _env;
        private string? serverdestinationpath { get; set; }
        public ManagerDashboardController(IUnitOfWork uow, IWebHostEnvironment env) : base(uow)
        {
            _env = env;
        }
        #endregion
        // GET: Admin/Movies
        public IActionResult Index()
        {   
            DashboardDto dashboardDto = new DashboardDto();
            var totalorder = _uow.Orders.GetAll().Count();
            var pendingorder = _uow.Orders.GetAll(p => p.Order_Status == "Pending").Count();
            var paidorder = _uow.Orders.GetAll(p => p.Order_Status == "Paid").Count();
            var shippingorder = _uow.Orders.GetAll(p => p.Order_Status == "Shipping").Count();
            var users = _uow.ApplicationUsers.GetAll();
            var customerid = _uow.ApplicationUsers.GetUserRole("Customer");
            var customercount = 0;
            var managerid = _uow.ApplicationUsers.GetUserRole("Manager");
            var managercount = 0;
            var adminid = _uow.ApplicationUsers.GetUserRole("Admin");
            var admincount = 0;
            var totaluser = users.Count();
            foreach(var user in users){
                var checkrole = _uow.ApplicationUsers.CheckRole(user.Id);
                if(checkrole == customerid){
                    customercount++;
                }else if(checkrole == managerid){
                    managercount++;
                }else{
                    admincount++;
                }
            }
            var orders = _uow.Orders.GetAll(p => p.Order_Status == "Paid");
            decimal dec = 0;
            foreach (var order in orders)
            {
                dec = (decimal)(dec + order.Total_Price)!;
            }
            int totalearnings = (int)Math.Round(dec);
            var totalcategory = _uow.Categories.GetAll().Count();
            var totalsubcategory = _uow.SubCategories.GetAll().Count();
            var totalproduct = _uow.Products.GetAll().Count();
            dashboardDto.Total_Order = totalorder;
            dashboardDto.Pending_Order = pendingorder;
            dashboardDto.Paid_Order = paidorder;
            dashboardDto.Shipping_Order = shippingorder;
            dashboardDto.Total_User = totaluser;
            dashboardDto.Customer = customercount;
            dashboardDto.Manager = managercount;
            dashboardDto.Admin = admincount;
            dashboardDto.Total_Earnings = totalearnings;
            dashboardDto.Total_Category = totalcategory;
            dashboardDto.Total_Subcategory = totalsubcategory;
            dashboardDto.Total_Product = totalproduct;
            return View(dashboardDto);
        }
        
        public IActionResult ManageUsers(int id = 1, string role = null!){
            if(role == null || role == "All"){
                Console.WriteLine("if");
                UserParam userParam = new UserParam{
                PageIndex = id, PageSize = 10
                };
                Task<UserVM> users = _uow.ApplicationUsers.GetUsersByPaging(userParam);
                ViewData["SelectedValue"] = role;
                return View(users.Result);
            }
            else{
                Console.WriteLine("else");
                UserParam userParam = new UserParam{
                PageIndex = id, PageSize = 10
                };
                Task<UserVM> users = _uow.ApplicationUsers.GetUsersByPaging2(userParam, role);
                ViewData["SelectedValue"] = role;
                return View(users.Result);
            }
        }
        public IActionResult ManageCategories(){
            var categories = _uow.Categories.GetCategories();
            return View(categories);
        }
        public IActionResult CreateCategory(){
            Category category;
            category = _uow.Categories.CreateCategory();
            _uow.Categories.Add(category);
            _uow.Save();
            return RedirectToAction(nameof(ManageCategories));
        }
        public IActionResult AddSubCategory(int id){
            SubCategory subCategory;
            subCategory = _uow.SubCategories.CreateSubCategory(id);
            _uow.SubCategories.Add(subCategory);
            _uow.Save();
            return RedirectToAction(nameof(ManageCategories));
        }
        public IActionResult CategoryDetails(int id){
            Category category;
            category = _uow.Categories.Get(id);
            return View("EditCategory", category);
        }
        [HttpPost]
        public IActionResult EditCategory(int categoryid, string categoryname, IFormFile categoryimage){
                string webRootPath = _env.WebRootPath;
                string inputfilename = String.Format("Category-{0}.jpg", categoryid);
                string uploadsPath = Path.Combine("images", "CategoryImages", inputfilename);
                string filePath = Path.Combine(webRootPath, uploadsPath);
            if(categoryimage == null || categoryimage?.Length == 0){            
                Category category = new Category();
                category = _uow.Categories.Get(categoryid);
                category.CategoryId = categoryid;
                category.Category_Name = categoryname;
                category.Category_Image = category.Category_Image;
                _uow.Categories.Update(category);
                _uow.Save();
                return RedirectToAction(nameof(ManageCategories));
            } else{
                using(FileStream stream = new FileStream(filePath, FileMode.Create)){
                    categoryimage?.CopyTo(stream);
                }
                Category category = new Category();
                category.CategoryId = categoryid;
                category.Category_Name = categoryname;
                string uploadsPath2 = uploadsPath.Replace("\\","/");
                category.Category_Image = uploadsPath2;
                _uow.Categories.Update(category);
                _uow.Save();
                return RedirectToAction(nameof(ManageCategories));
            }
        }
        [HttpPost]
        public IActionResult UpdateSubCategory(int subcategoryid, int categoryid, string subcategoryname){
            SubCategory subCategory = new SubCategory();
            subCategory.SubCategoryId = subcategoryid;
            subCategory.Category_Id = categoryid;
            subCategory.SubCategory_Name = subcategoryname;
            _uow.SubCategories.Update(subCategory);
            _uow.Save();
            return RedirectToAction(nameof(ManageCategories));
        }
        public IActionResult ManageProducts(int id = 1, int categoryid = 0, int subcategoryid = 0){
            var categories = _uow.Categories.GetAll();
            ViewData["Categories"] = categories;
            if(categoryid == 0){
                Param param = new Param{
                    PageIndex = id, PageSize = 10
                };
                Task<ProductVM> products = _uow.Products.GetProductsByPaging(param);
                ViewData["selectedCategory"] = "All";
                ViewData["subcategory"] = null;
                ViewData["selectedSubcategory"] = null;
                return View(products.Result);
            }else if(categoryid != 0 && subcategoryid == 0){
                var categoryname = _uow.Categories.Get(categoryid).Category_Name;
                var subcategories = _uow.SubCategories.GetAll(p => p.Category_Id == categoryid);
                Param param = new Param{
                    PageIndex = id, PageSize = 10
                };
                Task<ProductVM> products = _uow.Products.GetProductsByPaging2(param, categoryid);
                ViewData["selectedCategory"] = categoryname;
                ViewData["subcategory"] = subcategories;
                ViewData["selectedSubcategory"] = null;
                return View(products.Result);
            }else{
                var categoryname = _uow.Categories.Get(categoryid).Category_Name;
                var subcategories = _uow.SubCategories.GetAll(p => p.Category_Id == categoryid);
                string selectedsubcategory = null!;
                foreach (var item in subcategories)
                {
                    if(item.SubCategoryId == subcategoryid){
                        selectedsubcategory = item.SubCategory_Name!;
                        break;
                    }
                }
                Param param = new Param{
                    PageIndex = id, PageSize = 10
                };
                Task<ProductVM> products = _uow.Products.GetProductsByPaging3(param, subcategoryid);
                ViewData["selectedCategory"] = categoryname;
                ViewData["subcategory"] = subcategories;
                ViewData["selectedSubcategory"] = selectedsubcategory;
                return View(products.Result);
            }
        }
        public IActionResult CreateProduct(){
            Product product;
            product = _uow.Products.CreateProduct();
            _uow.Products.Add(product);
            _uow.Save();
            return RedirectToAction(nameof(ManageProducts));
        }
        public IActionResult ProductDetails(int id, bool isPhoto = false){
            var product = _uow.Products.Get(id);
            var subcategory = _uow.SubCategories.Get(product.SubCategory_Id);

Walmart.Web/Areas/Manager/Views/ManagerDashboard/ManageCategories.cshtml
@model List<Walmart.ApplicationCore.DtoModels.CategoryDto>
<div class="pcoded-main-container">
    <div class="pcoded-content">
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">Dashboard Analytics</h5>
                        </div>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index.html"><i class="fa-solid fa-house"></i></a></li>
                            <li class="breadcrumb-item"><a href="#!">Manage Categories</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-6 col-md-12" style="top: -90px;left:10px;max-width:98.5%">
        <div class="card table-card">
            <div class="alert alert-dismissible fade show" role="alert" style="margin:12px 12px 0 12px;display:none" id="alert">
                <strong id="alerttext"></strong>
                <button type="button" class="close" data-bs-dismiss="alert" style="top: -3px">
                    <span aria-hidden="true">x</span>
                </button>
            </div>
            <div class="card-header">
                <h5>Manage Categories</h5>
                <div class="card-header-right">
                    <div class="btn-group card-option">
                        <a class="btn btn-primary rounded" asp-controller="ManagerDashboard" asp-action="CreateCategory" asp-area="Manager">Create Category</a>
                    </div>
                </div>
            </div>
            <div class="card-body p-0">
                <div class="table-responsive">
                    <div class="row row-cols-2" style="width:100%;margin-right:0;margin-left:0;padding-bottom:10px">
                        @foreach (var category in Model)
                        {
                        <div class="col column1 cate1" id="category_@category.CategoryId">
                            <div>
                                <span style="font-weight: 700; font-size: 18px">@category.Category_Name</span>
                                <span style="float: right;margin-top:3px">
                                    <a class="fa-solid fa-plus text-primary" href="@Url.Action("AddSubCategory", "ManagerDashboard", new { id = @category.CategoryId})"></a>
                                    <a class="fa-solid fa-pen-to-square text-warning" style="margin-left: 8px;" href="@Url.Action("CategoryDetails", "ManagerDashboard", new { id = @category.CategoryId})"></a>
                                </span>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-6" style="flex-grow: 1;max-width:75%">
                                @if(category?.SubCategories != null){
                                @foreach (var item in category.SubCategories)
                                {
                                    <form method="post" asp-action="UpdateSubCategory" onsubmit="return checknull3(@item.SubCategoryId)">
                                        <div class="form-group" id="subcategory_@item.SubCategoryId">
                                            <input type="text" name="categoryid" value="@item.Category_Id" style="display: none;">
                                            <input type="text" name="subcategoryid" value="@item.SubCategoryId" style="display: none;">
                                            <span id="@item.SubCategoryId">@item.SubCategory_Name</span>
                                            <p class="text-danger" style="margin:0 0 3px 0;display:none" id="warn-@item.SubCategoryId">SubCategory name can't be empty !</p>
                                            <span style="margin-top:3px">
                                            <button type="submit" class="fa-solid fa-check text-primary" style="outline:none;background-color:white;border:none;padding:0px;display:none" id="checkmark-@item.SubCategoryId"></button>
                                            <button type="button" class="fa-solid fa-pen-to-square text-warning" style="margin-left: 8px;border: none;padding: 0;background-color: white;outline:none" onclick="replacewithinput(@item.SubCategoryId)"></button>
                                            </span>
                                        </div>
                                    </form>
                                }}
                                </div>
                                @if (category?.Category_Image != null)
                                {
                                    <img src="~/@category?.Category_Image" alt="" style="width: 140px;height:140px">
                                }
                            </div>
                        </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

Walmart.Web/Areas/Manager/Views/ManagerDashboard/ManageOrders.cshtml
@model Walmart.ApplicationCore.ViewModels.OrderVM;
@{
    int i = 0;
    var total = Model.Total;
    var Pages = total/10;
    int j = 0;
}
<div class="pcoded-main-container">
    <div class="pcoded-content">
        <!-- [ breadcrumb ] start -->
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">Dashboard Analytics</h5>
                        </div>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index.html"><i class="fa-solid fa-house"></i></a></li>
                            <li class="breadcrumb-item"><a href="#!">Manage Orders</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-6 col-md-12" style="top: -90px;left:10px;max-width:98.5%">
        <div class="card table-card">
            <div class="card-header">
                <h5>Manage Orders</h5>
                <h6 style="font-weight: 500;margin-top:10px">Sort by: Order's status</h6>
                <select id="statusSelect" style="width: 120px;" onchange="changestatus()">
                    <option>All</option>
                    <option>Pending</option>
                    <option>Processing</option>
                    <option>Shipping</option>
                    <option>Paid</option>
                    <option>Canceled</option>
                </select>
            </div>
            <div class="card-body p-0">
                <div class="table-responsive">
                    <table class="table table-hover mb-0">
                        <thead>
                            <tr>
                                <th>Order ID</th>
                                <th>Customer Name</th>
                                <th>Phone Number</th>
                                <th>Address</th>
                                <th>Create Date</th>
                                <th>Order Status</th>
                                <th>Payment Method</th>
                                <th>Total Price</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var order in Model.DataList)
                            {
                                <tr id="tr1">
                                    <td>@order.OrderId</td>
                                    <td>@order.Customer_Name</td>
                                    <td>@order.Phone_Number</td>
                                    <td>@order.Address</td>
                                    <td>@order.CreateDate</td>
                                    @if (order.Order_Status == "Pending")
                                    {
                                      <td><button class="btn btn-warning" style="padding: 4px 8px;">@order.Order_Status</button></td>
                                    }else if(order.Order_Status == "Processing"){
                                      <td><button class="btn btn-primary" style="padding: 4px 8px;">@order.Order_Status</button></td>
                                    }else if(order.Order_Status == "Shipping"){
                                      <td><button class="btn btn-info" style="padding: 4px 8px;">@order.Order_Status</button></td>
                                    }else if(order.Order_Status == "Paid"){
                                      <td><button class="btn btn-success" style="padding: 4px 8px;">@order.Order_Status</button></td>
                                    }else{
                                      <td><button class="btn btn-danger" style="padding: 4px 8px;">@order.Order_Status</button></td>
                                    }
                                    <td>@order.Payment_Method</td>
                                    <td>@order.Total_Price</td>
                                    <td>
                                        <a class="fa-solid fa-eye text-primary" style="margin-right: 12px;" href="@Url.Action("OrderDetails", "ManagerDashboard", new { id = @order.OrderId})"></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-6 col-md-12" style="top: -90px;left:10px;max-width:98.5%;display:flex;justify-content:center">
        @for (i = 0; i <= Pages; i++)
        {
            {
                j = i + 1;
            }
            <a href="@Url.Action("ManageOrders", "ManagerDashboard", new { id = @j})" style="border:1px solid grey;padding:10px 15px">@j</a>
        }
    </div>
<script>
    $(document).ready(function() {
        var selectedValue = '@(ViewData["SelectedValue"] as string)';
        
        if (selectedValue) {
            $('#statusSelect').val(selectedValue); // Set the selected value
        }
    });
</script>

Walmart.Web/Areas/Manager/Views/ManagerDashboard/ManageProducts.cshtml
@using Walmart.ApplicationCore.Models;
@model Walmart.ApplicationCore.ViewModels.ProductVM;
@{
    int i = 0;
    var total = Model.Total;
    var Pages = total/10;
    int j = 0;
    var categories = ViewData["Categories"] as List<Category>;
}
<div class="pcoded-main-container">
    <div class="pcoded-content">
        <!-- [ breadcrumb ] start -->
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">Dashboard Analytics</h5>
                        </div>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index.html"><i class="fa-solid fa-house"></i></a></li>
                            <li class="breadcrumb-item"><a href="#!">Manage Products</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-6 col-md-12" style="top: -90px;left:10px;max-width:98.5%">
        <div class="card table-card">
            <div class="alert alert-dismissible fade show" role="alert" style="margin:12px 12px 0 12px;display:none" id="alert">
                <strong id="alerttext">Delete product successfully !</strong>
                <button type="button" class="close" data-bs-dismiss="alert" style="top: -3px">
                    <span aria-hidden="true">x</span>
                </button>
            </div>
            <div class="card-header">
                <h5>Manage Products</h5>
                <div style="display: flex;">
                    <h6 style="font-weight: 500;margin-top:10px;margin-right:10px">Category: </h6>
                    <select id="category" style="width: 240px;height:fit-content;margin: auto 20px auto 0" onchange="changecategory()">
                        <option id="0">All</option>
                        @foreach (var category in categories!)
                        {
                            <option id="@category.CategoryId">@category.Category_Name</option>
                        }
                    </select>
                    <h6 style="font-weight: 500;margin-top:10px;margin-right:10px">Subcategory: </h6>
                    <select id="subcate" style="width: 240px;height:fit-content;margin: auto 0" onchange="changesubcategory()">
                        @if (ViewData["subcategory"] == null)
                        {
                            <option style="display: none;" selected>Please select a category</option>   
                        }else{
                            <option style="display: none;" selected>Select a subcategory</option>
                            @foreach (var subcategory in (List<SubCategory>)ViewData["subcategory"]!)
                            {
                                <option id="@subcategory.SubCategoryId">@subcategory.SubCategory_Name</option>
                            }
                        }
                    </select>
                </div>
                <div class="card-header-right">
                    <div class="btn-group card-option">
                        <a class="btn btn-primary rounded" asp-controller="ManagerDashboard" asp-action="CreateProduct" asp-area="Manager" onclick="checkcategory(event)">Create Product</a>
                    </div>
                </div>
            </div>
            <div class="card-body p-0">
                <div class="table-responsive">
                    <table class="table table-hover mb-0">
                        <thead>
                            <tr>
                                <th>Product Id</th>
                                <th>SubCategory Name</th>
                                <th>Product Name</th>
                                <th>Product Price</th>
                                <th>Product Status</th>
                                <th>Product Quantity</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var product in Model.DataList)
                            {
                                <tr class="tr1" id="@product.ProductId">
                                    <td>@product.ProductId</td>
                                    <td>@product.SubCategory_Name</td>
                                    <td>@product.Product_Name</td>
                                    <td>@product.Product_Price</td>
                                    <td>@product.Product_Status</td>
                                    <td>@product.Product_Quantity</td>
                                    <td>
                                        <a class="fa-solid fa-pen-to-square text-warning" style="margin-right: 12px;" href="@Url.Action("ProductDetails", "ManagerDashboard", new { id = @product.ProductId})"></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-6 col-md-12" style="top: -90px;left:10px;max-width:98.5%;display:flex;justify-content:center">
        @for (i = 0; i <= Pages; i++)
        {
            {
                j = i + 1;
            }
            <a href="@Url.Action("ManageProducts", "ManagerDashboard", new { id = @j})" style="border:1px solid grey;padding:10px 15px">@j</a>
        }
    </div>
<script>
    $(document).ready(function() {
        var selectedValue = '@Html.Raw(ViewData["selectedCategory"] as string)';
        if (selectedValue) {
            $('#category').val(selectedValue);
        }
        var selectedValue2 = '@Html.Raw(ViewData["selectedSubcategory"] as string)';
        var selectedValue3 = '@ViewData["selectedSubcategory"]';
        if (selectedValue3 != null && selectedValue3 !== "") {
            $('#subcate').val(selectedValue2); 
        }
    });
</script>

Walmart.Web/Areas/Manager/Views/ManagerDashboard/ManageUsers.cshtml
@model Walmart.ApplicationCore.ViewModels.UserVM;
@{
    int i = 0;
    var total = Model.Total;
    var Pages = total/10;
    int j = 0;
}
<div class="pcoded-main-container">
    <div class="pcoded-content">
        <!-- [ breadcrumb ] start -->
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">Dashboard Analytics</h5>
                        </div>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index.html"><i class="fa-solid fa-house"></i></a></li>
                            <li class="breadcrumb-item"><a href="#!">Manage Users</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-6 col-md-12" style="top: -90px;left:10px;max-width:98.5%">
        <div class="card table-card">
            <div class="card-header">
                <h5>Manage Users</h5>
                <h6 style="font-weight: 500;margin-top:10px">Sort by: User's role</h6>
                <select id="roleSelect" style="width: 120px;" onchange="changerole()">
                    <option>All</option>
                    <option>Customer</option>
                    <option>Manager</option>
                    <option>Admin</option>
                </select>
                <div class="card-header-right">
                    <div class="btn-group card-option">
                        
                    </div>
                </div>
            </div>
            <div class="card-body p-0">
                <div class="table-responsive">
                    <table class="table table-hover mb-0">
                        <thead>
                            <tr>
                                <th>User ID</th>
                                <th>FullName</th>
                                <th>Email</th>
                                <th>Phone Number</th>
                                <th>Address</th>
                                <th>Role</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                                @foreach (var user in Model.DataList)
                                {
                                <tr>
                                <td>@user.Id</td>
                                <td>@user.FullName</td>
                                <td>@user.Email</td>
                                <td>@user.PhoneNumber</td>
                                <td>@user.Address</td>
                                <td>@user.RoleName</td>
                                <td></td>
                                </tr>
                                }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-6 col-md-12" style="top: -90px;left:10px;max-width:98.5%;display:flex;justify-content:center">
        @for (i = 0; i <= Pages; i++)
        {
            {
                j = i + 1;
            }
            <a href="@Url.Action("ManageUsers", "ManagerDashboard", new { id = @j})" style="border:1px solid grey;padding:10px 15px">@j</a>
        }
    </div>
<script>
    $(document).ready(function() {
        var selectedValue = '@(ViewData["SelectedValue"] as string)';
        
        if (selectedValue) {
            $('#roleSelect').val(selectedValue); // Set the selected value
        }
    });
</script>